# Generated by scripts/brew-formula.sh — do not edit by hand.
#
# Homebrew is the convenient way in, not the checkable one. Before trusting a
# binary that will hold your signing keys:
#
#     gh release download --repo aithos-protocol/registry v0.2.0
#     gh attestation verify aithos-*.tar.gz --repo aithos-protocol/registry
#
class Aithos < Formula
  desc "Publish and verify signed A2A Agent Cards"
  homepage "https://github.com/aithos-protocol/registry"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/aithos-protocol/registry/releases/download/v0.2.0/aithos-0.2.0-aarch64-apple-darwin.tar.gz"
      sha256 "7663f887be9c88fee62ed59379bd36800b0ffdd8195be793c9881d4f68627be8"
    end
    on_intel do
      url "https://github.com/aithos-protocol/registry/releases/download/v0.2.0/aithos-0.2.0-x86_64-apple-darwin.tar.gz"
      sha256 "03cb68d203887046799e1f7fe16ce373e496378922d476ae7e92e4b83aa92183"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/aithos-protocol/registry/releases/download/v0.2.0/aithos-0.2.0-aarch64-unknown-linux-musl.tar.gz"
      sha256 "32cdfd38e372566a9c273eb15286fa091915b5121675e5f0231f2ef2c789cc9b"
    end
    on_intel do
      url "https://github.com/aithos-protocol/registry/releases/download/v0.2.0/aithos-0.2.0-x86_64-unknown-linux-musl.tar.gz"
      sha256 "685f74b1312a84f7e3a05bedc3bc84c74af04acec353edccc6955ae705b14a76"
    end
  end

  def install
    bin.install "aithos"
  end

  test do
    assert_match "0.2.0", shell_output("#{bin}/aithos --version")

    # A published entry this formula does not control, verified end to end:
    # if the strict parser, the canonicalizer or the JWS profile were broken by
    # a bad build, this fails rather than passing quietly.
    system bin/"aithos", "card", "init", "--out", "card.json"
    assert_match "valid", shell_output("#{bin}/aithos card check card.json")
  end
end
