# Generated by scripts/brew-formula.sh — do not edit by hand.
#
# Homebrew is the convenient way in, not the checkable one. Before trusting a
# binary that will hold your signing keys:
#
#     gh release download --repo aithos-protocol/registry v0.1.0-alpha.1
#     gh attestation verify aithos-*.tar.gz --repo aithos-protocol/registry
#
class Aithos < Formula
  desc "Publish and verify signed A2A Agent Cards"
  homepage "https://github.com/aithos-protocol/registry"
  version "0.1.0-alpha.1"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/aithos-protocol/registry/releases/download/v0.1.0-alpha.1/aithos-0.1.0-alpha.1-aarch64-apple-darwin.tar.gz"
      sha256 "4680be888ba67736effb7cab0a34195eb82041882b50d4463aeac7a8f7aca717"
    end
    on_intel do
      url "https://github.com/aithos-protocol/registry/releases/download/v0.1.0-alpha.1/aithos-0.1.0-alpha.1-x86_64-apple-darwin.tar.gz"
      sha256 "48b80ad31dbd6854fcd2ba0c53d2ad0328f338d2466e7b28a00299621d4020f8"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/aithos-protocol/registry/releases/download/v0.1.0-alpha.1/aithos-0.1.0-alpha.1-aarch64-unknown-linux-musl.tar.gz"
      sha256 "35175b7056ef448ac474111a0956f4642cd968c626d6c1242b159574cac6dafd"
    end
    on_intel do
      url "https://github.com/aithos-protocol/registry/releases/download/v0.1.0-alpha.1/aithos-0.1.0-alpha.1-x86_64-unknown-linux-musl.tar.gz"
      sha256 "235af14734e9693735edba3d80c97ec49bde871252661fb1cce2c8ed22f34a88"
    end
  end

  def install
    bin.install "aithos"
  end

  test do
    assert_match "0.1.0-alpha.1", shell_output("#{bin}/aithos --version")

    # A published entry this formula does not control, verified end to end:
    # if the strict parser, the canonicalizer or the JWS profile were broken by
    # a bad build, this fails rather than passing quietly.
    system bin/"aithos", "card", "init", "--out", "card.json"
    assert_match "valid", shell_output("#{bin}/aithos card check card.json")
  end
end
